Repository Geher-Marcell/Proj1-Epitmenyado-10A_B, pull requests merged in 2023-02, with the labels that each got.

#5 Jelek cseréje, kész
  README.md
Labels: documentation

#12 readme átírása
  README.md
Labels: Nem Sürgős

#16 13 1 feladat
  __pycache__/haz.cpython-310.pyc
  __pycache__/megoldas.cpython-310.pyc
  feladat.pdf
  haz.py
  main.py
  megoldas.py
  utca.txt
Labels: Feladat

#34 33 Kiírás, .gitignore
  .gitignore
  main.py
  megoldas.py
Labels: Fix

#43 \t-k javítása
  megoldas.py
Labels: Fix

#45 ado fuction áthelyezve
  haz.py
  megoldas.py
Labels: Sürgős, Optimalizálás, Fix

#52 unit test kész
  test_epitmenyado.py
Labels: Feladat, Fájl hozzáadása
